### PR TITLE
rename build-tree in Parser.pm6

### PR DESCRIPTION
**Pull request by tbrowder**
missed a rename in the original PR

### CODE REVIEW

**Comment by drforr** [comment]
Hopefully that's what was causing Travis to die - I really need to look at these diffs myself before committing. Still, I'm pleased beyond words that someone else is interested in this project and wants to actually use it in something approximating real-world code. Thank you very much for your time and input, I'm just sorry that I've been a bit off lately.

**Comment by tbrowder** [comment]
My pleasure, stumbled on a quick fix just so I can play with it.  I'm sorry you aren't presenting in DC, I must have misread the schedule.

**Comment by drforr** [comment]
Oh, it was a recent change due to some immigration issues, no worries.
I'm sorry I can't make it, it'll be the first time in years.

On Tue, Jun 13, 2017, at 02:08 PM, Tom Browder wrote:
> My pleasure, stumbled on a quick fix just so I can play with it.  I'm
> sorry you aren't presenting in DC, I must have misread the schedule.> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/drforr/perl6-Perl6-Parser/pull/12#issuecomment-308083077

**Comment by tbrowder** [comment]
Note that my PR is passing the tests

**Comment by tbrowder** [comment]
On Fri, Oct 6, 2017 at 4:26 AM, Jeff Goff <notifications@github.com> wrote:
> Merged #12.

Thank you!  I look forward to using this module.

**Pull request merged**
